name: Blob Build

on:
  push:
    branches:
      - master
      - experimental

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: temurin

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build with Gradle
        run: ./gradlew clean shadowJar

      - name: Rename jar file
        run: mv build/libs/ExtraHeads-*.jar build/libs/ExtraHeads.jar

      - name: Upload to Blob Builds (Dev)
        uses: WalshyDev/blob-builds/gh-action@main
        if: github.ref == 'refs/heads/master'
        with:
          project: ExtraHeads
          releaseChannel: Dev
          file: ./build/libs/ExtraHeads.jar
          apiToken: ${{ secrets.BLOB_BUILDS_API_TOKEN }}
          releaseNotes: ${{ github.event.head_commit.message }}

      - name: Upload to Blob Builds (Experimetal)
        uses: WalshyDev/blob-builds/gh-action@main
        if: github.ref == 'refs/heads/experimental'
        with:
          project: ExtraHeads
          releaseChannel: Experimental
          file: ./build/libs/ExtraHeads.jar
          apiToken: ${{ secrets.BLOB_BUILDS_API_TOKEN }}
          releaseNotes: ${{ github.event.head_commit.message }}
